find_library (LIBPCAP pcap PATHS /usr/lib/x86_64-linux-gnu)
find_library (LIBPTHREAD pthread)
macro (add_sponge_exec exec_name)
    add_executable ("${exec_name}" "${exec_name}.cc")
    target_link_libraries ("${exec_name}" ${ARGN} sponge ${LIBPTHREAD})
endmacro (add_sponge_exec)
